kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.serviceName | default .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Release.Name }}
  {{- if .Values.ports.external }}
  type: NodePort
  {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.internal }}
      targetPort: {{ .Chart.Name }}
      {{- if .Values.ports.external }}
      nodePort: {{ .Values.ports.external }}
      {{- end }}
